var _;
_ = Uint16Array.length;
_ = Uint16Array.name;
_ = Uint16Array.prototype;
_ = Uint16Array.BYTES_PER_ELEMENT;
Uint16Array.length = {};
Uint16Array.name = {};
Uint16Array.prototype = {};
Uint16Array.BYTES_PER_ELEMENT = {};
new Uint16Array();
