Object();
Object.assign('foo');
Object.getOwnPropertyDescriptor({foo: 'foo'});
Object.getOwnPropertyDescriptors({foo: 'foo'});
Object.getOwnPropertyNames({foo: 'foo'});
Object.getOwnPropertySymbols({foo: 'foo'});
Object.is();
Object.preventExtensions();
Object.seal();
Object.create({foo: 'foo'});
//Object.defineProperties();
//Object.defineProperty();
Object.freeze();
Object.getPrototypeOf({foo: 'foo'});
//Object.setPrototypeOf();
Object.isExtensible();
Object.isFrozen();
Object.isSealed();
Object.keys({foo: 'foo'});
Object.entries({foo: 'foo'});
Object.values({foo: 'foo'});
Object.length = {};
Object.name = {};
Object.prototype = {};
Object.assign = {};
Object.getOwnPropertyDescriptor = {};
Object.getOwnPropertyDescriptors = {};
Object.getOwnPropertyNames = {};
Object.getOwnPropertySymbols = {};
Object.is = {};
Object.preventExtensions = {};
Object.seal = {};
Object.create = {};
Object.defineProperties = {};
Object.defineProperty = {};
Object.freeze = {};
Object.getPrototypeOf = {};
Object.setPrototypeOf = {};
Object.isExtensible = {};
Object.isFrozen = {};
Object.isSealed = {};
//Object.keys = {};
Object.entries = {};
Object.values = {};
