var _;
_ = Promise.length;
_ = Promise.name;
_ = Promise.prototype;
_ = Promise.all;
_ = Promise.race;
_ = Promise.resolve;
_ = Promise.reject;
Promise.length = {};
Promise.name = {};
Promise.prototype = {};
Promise.all = {};
Promise.race = {};
Promise.resolve = {};
Promise.reject = {};
