var _;
_ = Reflect.defineProperty;
_ = Reflect.deleteProperty;
_ = Reflect.apply;
_ = Reflect.construct;
_ = Reflect.get;
_ = Reflect.getOwnPropertyDescriptor;
_ = Reflect.getPrototypeOf;
_ = Reflect.has;
_ = Reflect.isExtensible;
_ = Reflect.ownKeys;
_ = Reflect.preventExtensions;
_ = Reflect.set;
_ = Reflect.setPrototypeOf;
