var _;
_ = Date.length;
_ = Date.name;
_ = Date.prototype;
_ = Date.now;
_ = Date.parse;
_ = Date.UTC;
Date.length = {};
Date.name = {};
Date.prototype = {};
Date.now = {};
Date.parse = {};
Date.UTC = {};
