var _;
_ = Proxy.length;
_ = Proxy.name;
_ = Proxy.arguments;
_ = Proxy.caller;
_ = Proxy.revocable;
Proxy.length = {};
Proxy.name = {};
Proxy.arguments = {};
Proxy.caller = {};
Proxy.revocable = {};
