DTRACE_HTTP_CLIENT_REQUEST.length = {};
DTRACE_HTTP_CLIENT_REQUEST.name = {};
DTRACE_HTTP_CLIENT_REQUEST.arguments = {};
DTRACE_HTTP_CLIENT_REQUEST.caller = {};
DTRACE_HTTP_CLIENT_REQUEST.prototype = {};
