process._startProfilerIdleNotifier();
process._stopProfilerIdleNotifier();
process._getActiveRequests();
process._getActiveHandles();
process.reallyExit();
process.abort();
process.chdir();
process.cwd();
process.umask();
process.getuid();
process.geteuid();
process.setuid();
process.seteuid();
process.setgid();
process.setegid();
process.getgid();
process.getegid();
process.getgroups();
process.setgroups();
process.initgroups();
process._kill();
process._debugProcess();
process._debugPause();
process._debugEnd();
process.hrtime();
process.cpuUsage();
process.dlopen();
process.uptime();
process.memoryUsage();
process.binding();
process._linkedBinding();
process._setupDomainUse();
process._rawDebug();
process._fatalException();
process.assert();
process.emitWarning();
process.nextTick();
process._tickCallback();
process._tickDomainCallback();
process.openStdin();
process.exit();
process.kill();
process.title = {};
process.version = {};
process.moduleLoadList = {};
process.versions = {};
process._promiseRejectEvent = {};
process.arch = {};
process.platform = {};
process.release = {};
process.argv = {};
process.execArgv = {};
process.env = {};
process.pid = {};
process.features = {};
process._needImmediateCallback = {};
process.execPath = {};
process.debugPort = {};
process._startProfilerIdleNotifier = {};
process._stopProfilerIdleNotifier = {};
process._getActiveRequests = {};
process._getActiveHandles = {};
process.reallyExit = {};
process.abort = {};
process.chdir = {};
process.cwd = {};
process.umask = {};
process.getuid = {};
process.geteuid = {};
process.setuid = {};
process.seteuid = {};
process.setgid = {};
process.setegid = {};
process.getgid = {};
process.getegid = {};
process.getgroups = {};
process.setgroups = {};
process.initgroups = {};
process._kill = {};
process._debugProcess = {};
process._debugPause = {};
process._debugEnd = {};
process.hrtime = {};
process.cpuUsage = {};
process.dlopen = {};
process.uptime = {};
process.memoryUsage = {};
process.binding = {};
process._linkedBinding = {};
process._setupDomainUse = {};
process._events = {};
process._rawDebug = {};
process._eventsCount = {};
process.domain = {};
process._maxListeners = {};
process._fatalException = {};
process._exiting = {};
process.assert = {};
process.config = {};
process.emitWarning = {};
process.nextTick = {};
process._tickCallback = {};
process._tickDomainCallback = {};
process.stdout = {};
process.stderr = {};
process.stdin = {};
process.openStdin = {};
process.exit = {};
process.kill = {};
process.argv0 = {};
process.mainModule = {};
