var foo = {foo : 'foo'};

constructor();
constructor.assign(foo);
constructor.getOwnPropertyDescriptor(foo);
constructor.getOwnPropertyDescriptors(foo);
constructor.getOwnPropertyNames(foo);
constructor.getOwnPropertySymbols(foo);
constructor.is(foo);
constructor.preventExtensions(foo);
constructor.seal(foo);
constructor.create(foo);
//constructor.defineProperties(foo);
//constructor.defineProperty(foo);
constructor.freeze(foo);
constructor.getPrototypeOf(foo);
//constructor.setPrototypeOf(foo);
constructor.isExtensible(foo);
constructor.isFrozen(foo);
constructor.isSealed(foo);
constructor.keys(foo);
constructor.entries(foo);
constructor.values(foo);

constructor.length = {};
constructor.name = {};
constructor.prototype = {};
constructor.assign = {};
constructor.getOwnPropertyDescriptor = {};
constructor.getOwnPropertyDescriptors = {};
constructor.getOwnPropertyNames = {};
constructor.getOwnPropertySymbols = {};
constructor.is = {};
constructor.preventExtensions = {};
constructor.seal = {};
constructor.create = {};
constructor.defineProperties = {};
constructor.defineProperty = {};
constructor.freeze = {};
constructor.getPrototypeOf = {};
constructor.setPrototypeOf = {};
constructor.isExtensible = {};
constructor.isFrozen = {};
constructor.isSealed = {};
//constructor.keys = {};
constructor.entries = {};
constructor.values = {};
