var _;
_ = DTRACE_HTTP_CLIENT_REQUEST.length;
_ = DTRACE_HTTP_CLIENT_REQUEST.name;
_ = DTRACE_HTTP_CLIENT_REQUEST.arguments;
_ = DTRACE_HTTP_CLIENT_REQUEST.caller;
_ = DTRACE_HTTP_CLIENT_REQUEST.prototype;
