var _;
_ = DTRACE_NET_SERVER_CONNECTION.length;
_ = DTRACE_NET_SERVER_CONNECTION.name;
_ = DTRACE_NET_SERVER_CONNECTION.arguments;
_ = DTRACE_NET_SERVER_CONNECTION.caller;
_ = DTRACE_NET_SERVER_CONNECTION.prototype;
