var _;
_ = Intl.DateTimeFormat;
_ = Intl.NumberFormat;
_ = Intl.Collator;
_ = Intl.v8BreakIterator;
_ = Intl.getCanonicalLocales;
Intl.DateTimeFormat();
Intl.NumberFormat();
Intl.Collator();
Intl.v8BreakIterator();
Intl.getCanonicalLocales();
