var _;
_ = String.length;
_ = String.name;
_ = String.prototype;
_ = String.fromCharCode;
_ = String.fromCodePoint;
_ = String.raw;
String();
String.fromCharCode();
String.fromCodePoint();
String.raw`Hi\u000A!`;
