var _;
_ = process.title;
_ = process.version;
_ = process.moduleLoadList;
_ = process.versions;
_ = process._promiseRejectEvent;
_ = process.arch;
_ = process.platform;
_ = process.release;
_ = process.argv;
_ = process.execArgv;
_ = process.env;
_ = process.pid;
_ = process.features;
_ = process._needImmediateCallback;
_ = process.execPath;
_ = process.debugPort;
_ = process._startProfilerIdleNotifier;
_ = process._stopProfilerIdleNotifier;
_ = process._getActiveRequests;
_ = process._getActiveHandles;
_ = process.reallyExit;
_ = process.abort;
_ = process.chdir;
_ = process.cwd;
_ = process.umask;
_ = process.getuid;
_ = process.geteuid;
_ = process.setuid;
_ = process.seteuid;
_ = process.setgid;
_ = process.setegid;
_ = process.getgid;
_ = process.getegid;
_ = process.getgroups;
_ = process.setgroups;
_ = process.initgroups;
_ = process._kill;
_ = process._debugProcess;
_ = process._debugPause;
_ = process._debugEnd;
_ = process.hrtime;
_ = process.cpuUsage;
_ = process.dlopen;
_ = process.uptime;
_ = process.memoryUsage;
_ = process.binding;
_ = process._linkedBinding;
_ = process._setupDomainUse;
_ = process._events;
_ = process._rawDebug;
_ = process._eventsCount;
_ = process.domain;
_ = process._maxListeners;
_ = process._fatalException;
_ = process._exiting;
_ = process.assert;
_ = process.config;
_ = process.emitWarning;
_ = process.nextTick;
_ = process._tickCallback;
_ = process._tickDomainCallback;
_ = process.stdout;
_ = process.stderr;
_ = process.stdin;
_ = process.openStdin;
_ = process.exit;
_ = process.kill;
_ = process.argv0;
_ = process.mainModule;
process._startProfilerIdleNotifier();
process._stopProfilerIdleNotifier();
process._getActiveRequests();
process._getActiveHandles();
process.reallyExit();
process.abort();
process.chdir();
process.cwd();
process.umask();
process.getuid();
process.geteuid();
process.setuid();
process.seteuid();
process.setgid();
process.setegid();
process.getgid();
process.getegid();
process.getgroups();
process.setgroups();
process.initgroups();
process._kill();
process._debugProcess();
process._debugPause();
process._debugEnd();
process.hrtime();
process.cpuUsage();
process.dlopen();
process.uptime();
process.memoryUsage();
process.binding();
process._linkedBinding();
process._setupDomainUse();
process._rawDebug();
process._fatalException();
process.assert();
process.emitWarning();
process.nextTick();
process._tickCallback();
process._tickDomainCallback();
process.openStdin();
process.exit();
process.kill();
