DTRACE_NET_SERVER_CONNECTION.length = {};
DTRACE_NET_SERVER_CONNECTION.name = {};
DTRACE_NET_SERVER_CONNECTION.arguments = {};
DTRACE_NET_SERVER_CONNECTION.caller = {};
DTRACE_NET_SERVER_CONNECTION.prototype = {};
