console._stdout = {};
console._stderr = {};
console._ignoreErrors = {};
console._times = {};
console._stdoutErrorHandler = {};
console._stderrErrorHandler = {};
console.log = {};
console.info = {};
console.warn = {};
console.error = {};
console.dir = {};
console.time = {};
console.timeEnd = {};
console.trace = {};
console.assert = {};
console.clear = {};
console.count = {};
console.countReset = {};
console.group = {};
console.groupCollapsed = {};
console.groupEnd = {};
console.Console = {};
console.debug = {};
console.dirxml = {};
console.table = {};
console.markTimeline = {};
console.profile = {};
console.profileEnd = {};
console.timeline = {};
console.timelineEnd = {};
console.timeStamp = {};
console.context = {};
console._stdoutErrorHandler();
console._stderrErrorHandler();
console.log();
console.info();
console.warn();
console.error();
console.dir();
console.time();
console.timeEnd();
console.trace();
console.assert();
console.clear();
console.count();
console.countReset();
console.group();
console.groupCollapsed();
console.groupEnd();
console.Console();
console.debug();
console.dirxml();
console.table();
console.markTimeline();
console.profile();
console.profileEnd();
console.timeline();
console.timelineEnd();
console.timeStamp();
console.context();
