var _;
_ = DTRACE_HTTP_CLIENT_RESPONSE.length;
_ = DTRACE_HTTP_CLIENT_RESPONSE.name;
_ = DTRACE_HTTP_CLIENT_RESPONSE.arguments;
_ = DTRACE_HTTP_CLIENT_RESPONSE.caller;
_ = DTRACE_HTTP_CLIENT_RESPONSE.prototype;
