DTRACE_HTTP_SERVER_RESPONSE.length = {};
DTRACE_HTTP_SERVER_RESPONSE.name = {};
DTRACE_HTTP_SERVER_RESPONSE.arguments = {};
DTRACE_HTTP_SERVER_RESPONSE.caller = {};
DTRACE_HTTP_SERVER_RESPONSE.prototype = {};
