var _;
_ = Float32Array.length;
_ = Float32Array.name;
_ = Float32Array.prototype;
_ = Float32Array.BYTES_PER_ELEMENT;
Float32Array.length = {};
Float32Array.name = {};
Float32Array.prototype = {};
Float32Array.BYTES_PER_ELEMENT = {};
new Float32Array();
