var _;
_ = Reflect.defineProperty;
_ = Reflect.deleteProperty;
_ = Reflect.apply;
_ = Reflect.construct;
_ = Reflect.get;
_ = Reflect.getOwnPropertyDescriptor;
_ = Reflect.getPrototypeOf;
_ = Reflect.has;
_ = Reflect.isExtensible;
_ = Reflect.ownKeys;
_ = Reflect.preventExtensions;
_ = Reflect.set;
_ = Reflect.setPrototypeOf;
Reflect.defineProperty = {};
Reflect.deleteProperty = {};
Reflect.apply = {};
Reflect.construct = {};
Reflect.get = {};
Reflect.getOwnPropertyDescriptor = {};
Reflect.getPrototypeOf = {};
Reflect.has = {};
Reflect.isExtensible = {};
Reflect.ownKeys = {};
Reflect.preventExtensions = {};
Reflect.set = {};
Reflect.setPrototypeOf = {};
Reflect.defineProperty();
Reflect.deleteProperty();
Reflect.apply();
Reflect.construct();
Reflect.get();
Reflect.getOwnPropertyDescriptor();
Reflect.getPrototypeOf();
Reflect.has();
Reflect.isExtensible();
Reflect.ownKeys();
Reflect.preventExtensions();
Reflect.set();
Reflect.setPrototypeOf();
