var _;
_ = RegExp.length;
_ = RegExp.name;
_ = RegExp.prototype;
_ = RegExp.input;
_ = RegExp.$_;
_ = RegExp.lastMatch;
_ = RegExp.lastParen;
_ = RegExp.leftContext;
_ = RegExp.rightContext;
_ = RegExp.$1;
_ = RegExp.$2;
_ = RegExp.$3;
_ = RegExp.$4;
_ = RegExp.$5;
_ = RegExp.$6;
_ = RegExp.$7;
_ = RegExp.$8;
_ = RegExp.$9;
RegExp();
