var _;
_ = Object.length;
_ = Object.name;
_ = Object.prototype;
_ = Object.assign;
_ = Object.getOwnPropertyDescriptor;
_ = Object.getOwnPropertyDescriptors;
_ = Object.getOwnPropertyNames;
_ = Object.getOwnPropertySymbols;
_ = Object.is;
_ = Object.preventExtensions;
_ = Object.seal;
_ = Object.create;
_ = Object.defineProperties;
_ = Object.defineProperty;
_ = Object.freeze;
_ = Object.getPrototypeOf;
_ = Object.setPrototypeOf;
_ = Object.isExtensible;
_ = Object.isFrozen;
_ = Object.isSealed;
_ = Object.keys;
_ = Object.entries;
_ = Object.values;
Object();
Object.assign('foo');
Object.getOwnPropertyDescriptor('foo');
Object.getOwnPropertyDescriptors('foo');
Object.getOwnPropertyNames('foo');
Object.getOwnPropertySymbols('foo');
Object.is();
Object.preventExtensions();
Object.seal();
Object.create({foo: 'foo'});
//Object.defineProperties({foo: 'foo'});
//Object.defineProperty({foo: 'foo'});
Object.freeze();
Object.getPrototypeOf({foo: 'foo'});
//Object.setPrototypeOf({foo: 'foo'});
Object.isExtensible();
Object.isFrozen();
Object.isSealed();
Object.keys('foo');
Object.entries('foo');
Object.values('foo');
