Reflect.defineProperty = {};
Reflect.deleteProperty = {};
Reflect.apply = {};
Reflect.construct = {};
Reflect.get = {};
Reflect.getOwnPropertyDescriptor = {};
Reflect.getPrototypeOf = {};
Reflect.has = {};
Reflect.isExtensible = {};
Reflect.ownKeys = {};
Reflect.preventExtensions = {};
Reflect.set = {};
Reflect.setPrototypeOf = {};
Reflect.defineProperty();
Reflect.deleteProperty();
Reflect.apply();
Reflect.construct();
Reflect.get();
Reflect.getOwnPropertyDescriptor();
Reflect.getPrototypeOf();
Reflect.has();
Reflect.isExtensible();
Reflect.ownKeys();
Reflect.preventExtensions();
Reflect.set();
Reflect.setPrototypeOf();
