DTRACE_HTTP_CLIENT_RESPONSE.length = {};
DTRACE_HTTP_CLIENT_RESPONSE.name = {};
DTRACE_HTTP_CLIENT_RESPONSE.arguments = {};
DTRACE_HTTP_CLIENT_RESPONSE.caller = {};
DTRACE_HTTP_CLIENT_RESPONSE.prototype = {};
