var _;
_ = console._stdout;
_ = console._stderr;
_ = console._ignoreErrors;
_ = console._times;
_ = console._stdoutErrorHandler;
_ = console._stderrErrorHandler;
_ = console.log;
_ = console.info;
_ = console.warn;
_ = console.error;
_ = console.dir;
_ = console.time;
_ = console.timeEnd;
_ = console.trace;
_ = console.assert;
_ = console.clear;
_ = console.count;
_ = console.countReset;
_ = console.group;
_ = console.groupCollapsed;
_ = console.groupEnd;
_ = console.Console;
_ = console.debug;
_ = console.dirxml;
_ = console.table;
_ = console.markTimeline;
_ = console.profile;
_ = console.profileEnd;
_ = console.timeline;
_ = console.timelineEnd;
_ = console.timeStamp;
_ = console.context;
console._stdout = {};
console._stderr = {};
console._ignoreErrors = {};
console._times = {};
console._stdoutErrorHandler = {};
console._stderrErrorHandler = {};
console.log = {};
console.info = {};
console.warn = {};
console.error = {};
console.dir = {};
console.time = {};
console.timeEnd = {};
console.trace = {};
console.assert = {};
console.clear = {};
console.count = {};
console.countReset = {};
console.group = {};
console.groupCollapsed = {};
console.groupEnd = {};
console.Console = {};
console.debug = {};
console.dirxml = {};
console.table = {};
console.markTimeline = {};
console.profile = {};
console.profileEnd = {};
console.timeline = {};
console.timelineEnd = {};
console.timeStamp = {};
console.context = {};
console._stdoutErrorHandler();
console._stderrErrorHandler();
console.log();
console.info();
console.warn();
console.error();
console.dir();
console.time();
console.timeEnd();
console.trace();
console.assert();
console.clear();
console.count();
console.countReset();
console.group();
console.groupCollapsed();
console.groupEnd();
console.Console();
console.debug();
console.dirxml();
console.table();
console.markTimeline();
console.profile();
console.profileEnd();
console.timeline();
console.timelineEnd();
console.timeStamp();
console.context();
