var _;
_ = Uint32Array.length;
_ = Uint32Array.name;
_ = Uint32Array.prototype;
_ = Uint32Array.BYTES_PER_ELEMENT;
Uint32Array.length = {};
Uint32Array.name = {};
Uint32Array.prototype = {};
Uint32Array.BYTES_PER_ELEMENT = {};
new Uint32Array();
