var _;
_ = Int32Array.length;
_ = Int32Array.name;
_ = Int32Array.prototype;
_ = Int32Array.BYTES_PER_ELEMENT;
Int32Array.length = {};
Int32Array.name = {};
Int32Array.prototype = {};
Int32Array.BYTES_PER_ELEMENT = {};
new Int32Array();
