String.fromCharCode();
String.fromCodePoint();
String.raw`Hi\u000A!`;
String.length = {};
String.name = {};
String.prototype = {};
String.fromCharCode = {};
String.fromCodePoint = {};
String.raw = {};
String();
