Intl.DateTimeFormat = {};
Intl.NumberFormat = {};
Intl.Collator = {};
Intl.v8BreakIterator = {};
Intl.getCanonicalLocales = {};
Intl.DateTimeFormat();
Intl.NumberFormat();
Intl.Collator();
Intl.v8BreakIterator();
Intl.getCanonicalLocales();
