var _;
_ = Array.length;
_ = Array.name;
_ = Array.prototype;
_ = Array.isArray;
_ = Array.from;
_ = Array.of;
Array.length = {};
Array.name = {};
Array.prototype = {};
Array.isArray = {};
Array.from = {};
Array.of = {};
Array();
Array.isArray;
Array.from;
Array.of;
