var foo = {foo : 'foo'};

constructor();
constructor.assign(foo);
constructor.getOwnPropertyDescriptor(foo);
constructor.getOwnPropertyDescriptors(foo);
constructor.getOwnPropertyNames(foo);
constructor.getOwnPropertySymbols(foo);
constructor.is(foo);
constructor.preventExtensions(foo);
constructor.seal(foo);
constructor.create(foo);
//constructor.defineProperties(foo);
//constructor.defineProperty(foo);
constructor.freeze(foo);
constructor.getPrototypeOf(foo);
//constructor.setPrototypeOf(foo);
constructor.isExtensible(foo);
constructor.isFrozen(foo);
constructor.isSealed(foo);
constructor.keys(foo);
constructor.entries(foo);
constructor.values(foo);
